

old version
@startuml
actor Admin
participant "LibrarySystem" as LibrarySystem

activate Admin
Admin -> LibrarySystem: Click on "Login"
activate DataBase

LibrarySystem -> LibrarySystem: Enter username and password
     alt (Login details correct?)
     DataBase -> Admin: Admin logged in
     LibrarySystem -> Admin: Show welcome message
else (No)
     DataBase -> Admin: Show error message "Incorrect login details"
end

deactivate DataBase
deactivate Admin
@enduml





@startuml
actor Admin
participant "Library System" as LS
Admin -> LS: Enter admin username
Admin -> LS: Enter admin password
LS --> Admin: Admin login successful / Admin login error
@enduml















old version
@startuml
actor User
participant "LibrarySystem" as LibrarySystem

activate User
User -> LibrarySystem: Click on "Login"
activate Librarysystem

LibrarySystem -> LibrarySystem: Enter username and password
     alt (Login details correct?)
     Librarysystem -> User: User logged in
     LibrarySystem -> User: Show welcome message
else (No)
     Librarysystem -> User: Show error message "Incorrect login details"
end

deactivate Librarysystem
deactivate User
@enduml
